import Head from "next/head";

function Index() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by DesAIgner Team" />
        <link rel="icon" href="/DesAIgnerIco.ico" />
      </Head>
      <main>
        <div>About</div>
      </main>
    </>
  );
}

export default Index;