import Footer from "~/components/Footer";
import Head from "next/head";

function Index() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by DesAIgner Team" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex grow flex-col items-center justify-start font-coolveticaLight">
        <div>About</div>
      </main>
      <Footer />
    </>
  );
}

export default Index;
