import Head from "next/head";
import LoginForm from "~/components/LoginForm";
import LoginSwitch from "~/components/LoginSwitch";
import RegisterForm from "~/components/RegisterForm";
import { useState } from 'react'

function index() {

  const [login, setLogin] = useState(true);

  const toggleSwitch = () => {
    setLogin(!login);
  };

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by DesAIgner Team" />
        <link rel="icon" href="/DesAIgnerIco.ico" />
      </Head>
      <main className="mb-[100px] mt-[100px] flex flex-col grow items-center justify-center font-coolveticaLight">
        <div className="flex h-full w-full items-center justify-center">
          {login ? <LoginForm /> : <RegisterForm />}
        </div>
        <LoginSwitch login = {login} toggleSwitch = {toggleSwitch}/>
      </main>
    </>
  );
}

export default index;
