import Head from "next/head";
import LoginForm from "~/components/LoginForm";
import LoginSwitch from "~/components/LoginSwitch";
import RegisterForm from "~/components/RegisterForm";
import { useState } from "react";
import { useRouter } from "next/router";
import { useSession } from "next-auth/react";
import { motion } from "framer-motion";

const motionProps = {
  initial: "hidden",
  whileInView: "visible",
  viewport: { once: true },
  transition: { duration: 0.4 },
  variants: {
    visible: { opacity: 1, scale: 1, translateY: 0 },
    hidden: { opacity: 0, scale: 1, translateY: 22 },
  },
};

function Index() {
  const router = useRouter();
  const [login, setLogin] = useState(true);

  const { status } = useSession({
    required: false,
  });

  if (status === "loading") {
    return "Cargando...";
  }

  if (status === "authenticated") {
    void router.push("/home");
  }

  const toggleSwitch = () => {
    setLogin(!login);
  };

  if (status === "unauthenticated") {
    return (
      <>
        <Head>
          <title>Login</title>
          <meta name="description" content="Generated by DesAIgner Team" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex grow flex-col items-center justify-start font-coolveticaLight text-[#22302D] dark:text-[#FBF9FA]">
          <motion.div
            {...motionProps}
            className="flex h-full w-full items-center justify-center"
          >
            {login ? <LoginForm /> : <RegisterForm />}
          </motion.div>
          <LoginSwitch login={login} toggleSwitch={toggleSwitch} />
        </main>
      </>
    );
  }
}

export default Index;
