import Head from "next/head";
import RegisterForm from "~/components/RegisterForm";

function index() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by DesAIgner Team" />
        <link rel="icon" href="/DesAIgnerIco.ico" />
      </Head>
      <main className="mb-[100px] mt-[100px] font-coolveticaLight">
        <div className="flex h-full w-full items-center justify-center">
          <div className="flex h-[568px] w-[336px] items-center justify-center rounded-3xl bg-[#009E95] px-[12px]">
            <RegisterForm/>
          </div>
        </div>
      </main>
    </>
  );
}

export default index;
