import Head from "next/head";
import Footer from "~/components/Footer";

function index() {
  return (
    <>
      <Head>
        <title>Landing</title>
        <meta name="description" content="Generated by DesAIgner Team" />
        <link rel="icon" href="/DesAIgnerIco.ico" />
      </Head>
      <main className="flex grow flex-col items-center justify-start font-coolveticaLight">
        <h1 className="mx-[32px] mb-[52px] flex flex-wrap self-start font-coolveticaRegular text-[40px] leading-none text-[#FBF9FA]">
          Des
          <span className="bg-gradient-to-tr from-[#228187] to-[#59C3C3] bg-clip-text text-transparent">
            AI
          </span>
          gner, la app de
          <span className="bg-gradient-to-tr from-[#228187] to-[#59C3C3] bg-clip-text text-transparent">
            diseño de interiores
          </span>
        </h1>
        <h2 className="mx-[32px] mb-[52px] self-start font-coolveticaLight text-[20px] leading-none text-[#292F2D] text-transparent dark:text-[#FBF9FA]">
          Con Inteligencia Artificial, te ayudamos a crear el cuarto de tus sueños.
        </h2>
      </main>
      <Footer />
    </>
  );
}

export default index;
