import Head from "next/head";
import Footer from "~/components/Footer";

function index() {
  return (
    <>
      <Head>
        <title>Landing</title>
        <meta name="description" content="Generated by DesAIgner Team" />
        <link rel="icon" href="/DesAIgnerIco.ico" />
      </Head>
      <main>
        <div>Landing</div>
      </main>
      <Footer/>
    </>
  );
}

export default index;