import Head from "next/head";
import Footer from "~/components/Footer";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import { useSession } from "next-auth/react";
import ColecFolders from "~/components/collectionComps/ColecFolders";
import ColecDesign from "~/components/collectionComps/ColecDesign";

interface FolderKeys {
  favorito: boolean;
  id: number;
  nombre: string;
  disenios: object[];
}

type FolderType = FolderKeys[];

interface FolderDesignsKeys {
  coleccion: string;
}

type FolderDesigns = FolderDesignsKeys[];

function Index() {
  const router = useRouter();
  const [foldersInfo, setFoldersInfo] = useState<FolderType>();
  const [showFolder, setShowFolder] = useState(false);
  const [folderData, setFolderData] = useState<FolderDesigns | undefined>();

  useEffect(() => {
    fetch("api/auth/Colecciones", {
      method: "POST",
    })
      .then((response) => response.json())
      .then((data) => {
        // console.log(data);
        setFoldersInfo(data);
      })
      .catch((error: Error) => {
        console.log(error);
      });
  }, []);

  const { status } = useSession({
    required: false,
  });

  if (status === "loading") {
    return "Cargando...";
  }

  if (status === "unauthenticated") {
    void router.push("/login");
  }

  if (status === "authenticated") {
    return (
      <>
        <Head>
          <title>Collections</title>
          <meta name="description" content="Generated by DesAIgner Team" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex grow flex-col items-center justify-start font-coolveticaLight">
          {showFolder == false && (
            <ColecFolders
              foldersInfo={foldersInfo!}
              setShowFolder={setShowFolder}
              setFolderData={setFolderData}
            />
          )}
          {showFolder && <ColecDesign folderData={folderData} />}
        </main>
        <Footer />
      </>
    );
  }
}

export default Index;
