import Head from "next/head";

function index() {
  return (
    <>
      <Head>
        <title>Collections</title>
        <meta name="description" content="Generated by DesAIgner Team" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>Collections</div>
      </main>
    </>
  );
}

export default index;