import Head from "next/head";
import Footer from "~/components/Footer";
import { useRouter } from "next/router";
import { useSession } from "next-auth/react";

function index() {
  const router = useRouter();

  const { data: session, status } = useSession({
    required: false,
  });

  if (status === "loading") {
    return "Cargando...";
  }

  if (status === "unauthenticated") {
    router.push("/login");
  }

  if (status === "authenticated") {
    return (
      <>
        <Head>
          <title>Home</title>
          <meta name="description" content="Generated by DesAIgner Team" />
          <link rel="icon" href="/DesAIgnerIco.ico" />
        </Head>
        <main className="flex grow flex-col items-center justify-start font-coolveticaLight">
          <h1 className="mx-[32px] mb-[52px] self-start bg-gradient-to-tr from-[#228187] to-[#59C3C3] bg-clip-text font-coolveticaRegular text-[40px] leading-none text-transparent">
            Bienvenido
          </h1>
          <h2 className="mx-[32px] mb-[52px] self-start font-coolveticaRegular text-[#292F2D] dark:text-[#FBF9FA] text-[35px] leading-none text-transparent">Tus diseños recientes</h2>
        </main>
        <Footer />
      </>
    );
  }
}

export default index;
