import Footer from "~/components/Footer";
import Head from "next/head";
import ThemeButton from "~/components/ThemeButton";
import { useSession } from "next-auth/react";
import SignOutButton from "~/components/SignOutButton";
import DeleteAccountButton from "~/components/DeleteAccountButton";
import { motion } from "framer-motion";

const motionProps = {
  initial: "hidden",
  whileInView: "visible",
  viewport: { once: true },
  transition: { duration: 0.4 },
  variants: {
    visible: { opacity: 1, scale: 1, translateY: 0 },
    hidden: { opacity: 0, scale: 1, translateY: 22 },
  },
};

function Index() {
  const { status } = useSession({
    required: false,
  });

  return (
    <>
      <Head>
        <title>Settings</title>
        <meta name="description" content="Generated by DesAIgner Team" />
        <link rel="icon" href="/DesAIgnerIco.ico" />
      </Head>
      <main className="flex grow flex-col items-center justify-start font-coolveticaLight">
        <motion.h1
          {...motionProps}
          className="mx-[32px] mb-[30px] self-start font-coolveticaRegular text-[30px] leading-none text-[#22302D] dark:text-[#FBF9FA]"
        >
          Configuración
        </motion.h1>
        <ThemeButton />
        {status === "authenticated" && <SignOutButton />}
        {status === "authenticated" && <DeleteAccountButton />}
      </main>
      <Footer />
    </>
  );
}

export default Index;
