import Head from "next/head";
import ThemeButton from "~/components/ThemeButton";

function index() {
  return (
    <>
      <Head>
        <title>Settings</title>
        <meta name="description" content="Generated by DesAIgner Team" />
        <link rel="icon" href="/DesAIgnerIco.ico" />
      </Head>
      <main>
        <div className="mt-[500px]">Settings</div>
        <ThemeButton/>
      </main>
    </>
  );
}

export default index;