import Head from "next/head";
import Footer from "~/components/Footer";
import { useRouter } from "next/router";
import { useSession } from "next-auth/react";
import ImageUploader from "~/components/ImageUploader";
import CreateComboBox from "~/components/CreateComboBox";
import Presupuesto from "~/components/Presupuesto";
import Estilo from "~/components/Estilo";
import Plano from "~/components/Plano";
import Clima from "~/components/Clima";
import Discapacidad from "~/components/Discapacidad";

function index() {
  const router = useRouter();

  const { data: session, status } = useSession({
    required: false,
  });

  if (status === "loading") {
    return "Cargando...";
  }

  if (status === "unauthenticated") {
    router.push("/login");
  }

  if (status === "authenticated") {
    return (
      <>
        <Head>
          <title>Create</title>
          <meta name="description" content="Generated by DesAIgner Team" />
          <link rel="icon" href="/DesAIgnerIco.ico" />
        </Head>
        <main className="flex grow flex-col items-center justify-start font-coolveticaLight">
          <CreateComboBox icon={<Presupuesto/>} pholder="Presupuesto"/>
          <CreateComboBox icon={<Estilo/>} pholder="Estilo"/>
          <CreateComboBox icon={<Plano/>} pholder="Tipo"/>
          <CreateComboBox icon={<Clima/>} pholder="Clima"/>
          <CreateComboBox icon={<Discapacidad/>} pholder="Discapacidad"/>
          <ImageUploader/>
        </main>
        <Footer />
      </>
    );
  }
}

export default index;
