import Head from "next/head";
import Footer from "~/components/Footer";
import { useRouter } from "next/router";
import { useSession } from "next-auth/react";
import ImageUploader from "~/components/ImageUploader";
import CreateComboBox from "~/components/CreateComboBox";
import EmailLogo from "~/components/EmailLogo";

function index() {
  const router = useRouter();

  const { data: session, status } = useSession({
    required: false,
  });

  if (status === "loading") {
    return "Cargando...";
  }

  if (status === "unauthenticated") {
    router.push("/login");
  }

  if (status === "authenticated") {
    return (
      <>
        <Head>
          <title>Create</title>
          <meta name="description" content="Generated by DesAIgner Team" />
          <link rel="icon" href="/DesAIgnerIco.ico" />
        </Head>
        <main className="flex grow flex-col items-center justify-start font-coolveticaLight">
          <CreateComboBox icon={<EmailLogo/>} pholder="Presupuesto" name="presupuesto"/>
          <ImageUploader/>
        </main>
        <Footer />
      </>
    );
  }
}

export default index;
